import type { Language } from "../types";

export const mobileCopy = {
  en: {
    chapter: "Chapter",
    chapters: "Chapters",
    issue: "Portfolio / 2026",
    heroLabel: "NOOR / Graphic design journal",
    heroTitle: "Design with intention. Create with purpose.",
    heroBody: "Independent graphic design shaped through identity, packaging, print, editorial, and social work.",
    featuredLabel: "A curated exhibition",
    featuredTitle: "Selected work",
    featuredBody: "Real projects, each opened as its own visual chapter.",
    aboutLabel: "About Noor",
    aboutTitle: "A quiet eye for detail.",
    aboutBody: "Noor Bamarouf creates visual systems with clarity, feeling, and a careful sense of material.",
    servicesLabel: "Ways of working",
    servicesTitle: "Services",
    servicesBody: "Seven focused disciplines, connected by one clear visual point of view.",
    processLabel: "From thought to form",
    processTitle: "Process",
    processBody: "A measured five-step journey from the first conversation to final files.",
    archiveLabel: "The complete index",
    archiveTitle: "Project archive",
    archiveBody: "Eleven official projects across packaging, identity, print, and social design.",
    contactLabel: "Begin a conversation",
    contactTitle: "Have a project in mind?",
    contactBody: "Share the scope, timing, and feeling you want the work to hold.",
    projectStory: "Project story",
    visualSequence: "Visual sequence",
    finalFrame: "Final presentation",
    projectIndex: "Project index",
    allProjects: "All projects",
    menuLabel: "Mobile navigation",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    previous: "Previous project",
    next: "Next project",
    serviceReference: "Project reference",
    filterLabel: "Filter projects",
    year: "Year",
    copyright: "NOOR BAMAROUF. All rights reserved.",
  },
  ar: {
    chapter: "الفصل",
    chapters: "الفصول",
    issue: "ملف الأعمال / ٢٠٢٦",
    heroLabel: "نور / مجلة تصميم جرافيكي",
    heroTitle: "تصميم بنيّة واضحة. وصناعة لها معنى.",
    heroBody: "تصميم جرافيكي مستقل يتشكل عبر الهوية والتغليف والمطبوعات والتحرير والمنصات الاجتماعية.",
    featuredLabel: "معرض مختار",
    featuredTitle: "أعمال مختارة",
    featuredBody: "مشاريع حقيقية، يفتح كل منها فصلًا بصريًا مستقلًا.",
    aboutLabel: "عن نور",
    aboutTitle: "عين هادئة للتفاصيل.",
    aboutBody: "تصوغ نور بامعروف أنظمة بصرية تجمع الوضوح والشعور والعناية بالخامة.",
    servicesLabel: "مجالات العمل",
    servicesTitle: "الخدمات",
    servicesBody: "سبعة تخصصات مترابطة برؤية بصرية واضحة.",
    processLabel: "من الفكرة إلى الصورة",
    processTitle: "المنهجية",
    processBody: "خمس مراحل مدروسة تبدأ بالمحادثة وتنتهي بملفات منظمة وجاهزة.",
    archiveLabel: "الفهرس الكامل",
    archiveTitle: "أرشيف المشاريع",
    archiveBody: "أحد عشر مشروعًا رسميًا في التغليف والهوية والمطبوعات والتصميم الاجتماعي.",
    contactLabel: "ابدئي المحادثة",
    contactTitle: "هل لديكِ مشروع؟",
    contactBody: "شاركي نطاق المشروع وتوقيته والإحساس الذي تريدين أن يحمله.",
    projectStory: "قصة المشروع",
    visualSequence: "التسلسل البصري",
    finalFrame: "العرض الختامي",
    projectIndex: "فهرس المشاريع",
    allProjects: "كل المشاريع",
    menuLabel: "قائمة التنقل",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    previous: "المشروع السابق",
    next: "المشروع التالي",
    serviceReference: "مرجع من المشاريع",
    filterLabel: "تصفية المشاريع",
    year: "السنة",
    copyright: "نور بامعروف. جميع الحقوق محفوظة.",
  },
} satisfies Record<Language, Record<string, string>>;
