import type { Language } from "../types";

export const mobileCopy = {
  en: {
    menuLabel: "Mobile navigation",
    menuTitle: "NOOR BAMAROUF",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    chapterIntro: "Entry",
    chapterWork: "Selected work",
    chapterArchive: "Archive",
    chapterAbout: "About",
    chapterServices: "Services",
    chapterProcess: "Process",
    chapterContact: "Contact",
    projectStory: "Project story",
    projectWorld: "Project world",
    visualSequence: "Visual sequence",
    finalFrame: "Final frame",
    previous: "Previous",
    next: "Next",
    year: "Year",
    projects: "Projects",
    disciplines: "Disciplines",
    categories: "Categories",
    allProjects: "All projects",
    viewCase: "View project",
  },
  ar: {
    menuLabel: "قائمة التنقل",
    menuTitle: "نور بامعروف",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    chapterIntro: "الدخول",
    chapterWork: "أعمال مختارة",
    chapterArchive: "الأرشيف",
    chapterAbout: "عن نور",
    chapterServices: "الخدمات",
    chapterProcess: "المنهجية",
    chapterContact: "التواصل",
    projectStory: "قصة المشروع",
    projectWorld: "عالم المشروع",
    visualSequence: "التسلسل البصري",
    finalFrame: "المشهد الأخير",
    previous: "السابق",
    next: "التالي",
    year: "السنة",
    projects: "مشاريع",
    disciplines: "تخصصات",
    categories: "فئات",
    allProjects: "كل المشاريع",
    viewCase: "عرض المشروع",
  },
} satisfies Record<Language, Record<string, string>>;
