import type { Language } from "../types";

export const mobileCopy = {
  en: {
    chapters: "Chapters",
    chapter: "Chapter",
    featuredSelection: "A selected sequence",
    projectArchive: "Project archive",
    archiveIntro: "Twelve official projects across packaging, identity, print, and social design.",
    philosophyLabel: "A point of view",
    servicesLabel: "Ways of working",
    processLabel: "From thought to form",
    contactLabel: "Begin a conversation",
    previous: "Previous",
    next: "Next",
    viewProject: "View project",
    projectIndex: "Project index",
    selectedProject: "Selected project",
    image: "Image",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    menuLabel: "Navigation",
    scroll: "Scroll",
    allProjects: "All projects",
    servicePosition: "Service",
    detail: "Detail",
    projectStory: "Project story",
    finalFrame: "Final frame",
    profile: "NOOR BAMAROUF is an independent graphic designer shaping identities, packaging, print, and editorial systems through quiet detail.",
    contactNote: "Share the scope, timing, and feeling you want the work to hold.",
    copyright: "NOOR BAMAROUF. All rights reserved.",
  },
  ar: {
    chapters: "الفصول",
    chapter: "الفصل",
    featuredSelection: "تسلسل مختار",
    projectArchive: "أرشيف المشاريع",
    archiveIntro: "اثنا عشر مشروعًا رسميًا في التغليف والهوية والمطبوعات والتصميم الاجتماعي.",
    philosophyLabel: "وجهة نظر",
    servicesLabel: "مجالات العمل",
    processLabel: "من الفكرة إلى الصورة",
    contactLabel: "ابدئي المحادثة",
    previous: "السابق",
    next: "التالي",
    viewProject: "عرض المشروع",
    projectIndex: "فهرس المشاريع",
    selectedProject: "مشروع مختار",
    image: "صورة",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    menuLabel: "التنقل",
    scroll: "مرري",
    allProjects: "كل المشاريع",
    servicePosition: "الخدمة",
    detail: "تفصيل",
    projectStory: "قصة المشروع",
    finalFrame: "المشهد الختامي",
    profile: "نور بامعروف مصممة جرافيك مستقلة تصوغ الهويات والتغليف والمطبوعات والأنظمة التحريرية بعناية هادئة بالتفاصيل.",
    contactNote: "شاركي نطاق المشروع وتوقيته والإحساس الذي تريدين أن يحمله.",
    copyright: "نور بامعروف. جميع الحقوق محفوظة.",
  },
} satisfies Record<Language, Record<string, string>>;
